### ISSUE TITLE
余白とった方がいいかも

### ISSUE THREAD

**Issue by k-logic563** [fukutomirina/portfolio#3]
h3とh4の間がきついですね。
https://github.com/fukutomirina/portfolio/blob/ab466251a6e48817be9e0416627694483defc46f/index.html#L78-L79

**Comment by k-logic563** [comment]
ついでにh3とh4のfont-sizeが同じなので、h3よりh4は小さくした方がわかりやすいかなぁと思います！

**Comment by fukutomirina** [comment]
承知いたしました！
余白とフォントサイズを見直します✨
